"""v2.4.1: Generate RELEASE_VERIFICATION.md — release-time line/byte
manifest for critical files.

raw.githubusercontent.com を介して file を読む 3rd-party viewer / LLM
fetcher の一部が、長い text file を "1 line / collapsed" と誤表示する
事象が継続的に観測される (viewer 側 artifact、repo 側ではない)。
本 script は release tag 直前に走らせ、「この tag では各 file が
これだけの byte / LF / CR を持つ」という ground truth を生成する。

利用者・レビューア手順:

    1. 配布物の RELEASE_VERIFICATION.md (root) を見る
    2. 自分の viewer / tool で同じ file を取得し、行数・byte 数が
       一致するか確認する
    3. 不一致なら viewer 側 artifact が確定 (clean clone で再取得)

Usage:

    python scripts/release_verification.py > RELEASE_VERIFICATION.md
    python scripts/release_verification.py --check   # CI gate

`--check` mode では「全 file が CR=0, LF>=10」を確認し、違反があれば
exit 1 する。
"""
from __future__ import annotations
import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _read_repo_bytes(rel: str) -> bytes | None:
    """Return the bytes that git stores for `rel` (canonical form,
    LF-only on this repo thanks to `.gitattributes`). Falls back to
    working tree if not in a git repo."""
    try:
        out = subprocess.run(
            ["git", "show", f"HEAD:{rel}"],
            cwd=ROOT, capture_output=True, check=True,
        )
        return out.stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        p = ROOT / rel
        if not p.exists():
            return None
        return p.read_bytes()

# 「raw 表示問題」のレビュー指摘が頻発する critical files。
# new release では明示的に list に追加してから tag すること。
CRITICAL_FILES = [
    "README.md",
    "CHANGELOG.md",
    "src/lab_executor/__init__.py",
    "src/lab_executor/cli.py",
    "src/lab_executor/extension_paths.py",
    "src/lab_executor/extension_discovery.py",
    "src/lab_executor/extension_migration.py",
    "src/lab_executor/session.py",
    "src/lab_executor/job/manager.py",
    "src/lab_executor/server.py",
    "tests/test_v260_copy_plan.py",
    "tests/test_v250_migration_plan.py",
    "tests/test_v240_extension_dual_path.py",
    "tests/test_v230_extension_lifecycle.py",
    "tests/test_v220_cli_authoring.py",
    "tests/test_v210_server.py",
    "tests/test_v200_split.py",
]


def file_stats(rel: str) -> dict | None:
    """Stat a critical file as **git stores it** (LF-only canonical
    form), not the working tree (which on Windows may have CRLF)."""
    b = _read_repo_bytes(rel)
    if b is None:
        return None
    return {
        "path": rel,
        "bytes": len(b),
        "lf": b.count(b"\n"),
        "cr": b.count(b"\r"),
        "bom": b.startswith(b"\xef\xbb\xbf"),
    }


def _get_version() -> str:
    init = ROOT / "src" / "lab_executor" / "__init__.py"
    for line in init.read_text(encoding="utf-8").splitlines():
        if line.startswith("__version__"):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    return "unknown"


def render_markdown(rows: list[dict], version: str) -> str:
    lines = [
        f"# Release Verification - lab-executor-mcp v{version}",
        "",
        "This manifest is generated by `scripts/release_verification.py`",
        "at release tag time. Each row is the **ground truth** for the",
        "byte / LF / CR count of a critical file in this tag.",
        "",
        "## Why this exists",
        "",
        "Some 3rd-party viewers / LLM-based raw fetchers report files",
        "served via `raw.githubusercontent.com` as \"1 line / collapsed\".",
        "This is a **viewer-side artifact** and is independently",
        "falsifiable: clone the repo locally and compare your file",
        "counts to this manifest. If they don't match, the issue is on",
        "the viewer side. If they do match, the file is genuinely",
        "multi-line LF-only.",
        "",
        "## Verification command (any reviewer can run)",
        "",
        "```bash",
        "git clone --branch v" + version
        + " https://github.com/TECTOS-JP/lab-executor-mcp.git tmp",
        "cd tmp",
        "python scripts/release_verification.py --check",
        "# expect: \"OK\" + exit 0",
        "```",
        "",
        "Or via raw URL (single file):",
        "",
        "```bash",
        "curl -s https://raw.githubusercontent.com/TECTOS-JP/"
        "lab-executor-mcp/v" + version
        + "/src/lab_executor/extension_paths.py \\",
        "  | python -c \"import sys; b=sys.stdin.buffer.read(); "
        "print(f'bytes={len(b)} LF={b.count(chr(10).encode())} "
        "CR={b.count(chr(13).encode())}')\"",
        "```",
        "",
        "## Manifest",
        "",
        "| file | bytes | LF | CR | BOM |",
        "|---|--:|--:|--:|:--:|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['path']}` | {r['bytes']} | {r['lf']} | "
            f"{r['cr']} | {'YES' if r['bom'] else 'no'} |"
        )
    lines += [
        "",
        "## Invariants enforced by `--check`",
        "",
        "- All files: `CR == 0` (LF-only line endings)",
        "- All files: `LF >= 10` (genuinely multi-line)",
        "- All files: `BOM == no` (no UTF-8 BOM)",
        "",
        "If `--check` passes, any viewer reporting these files as",
        "\"1 line\" is wrong.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check", action="store_true",
        help="Verify invariants (CR=0, LF>=10, no BOM) and exit 1 on "
             "violation",
    )
    args = ap.parse_args()

    rows: list[dict] = []
    violations: list[str] = []
    for rel in CRITICAL_FILES:
        st = file_stats(rel)
        if st is None:
            violations.append(f"missing: {rel}")
            continue
        rows.append(st)
        if args.check:
            if st["cr"] != 0:
                violations.append(
                    f"CR>0: {rel} (cr={st['cr']})")
            if st["lf"] < 10:
                violations.append(
                    f"LF<10: {rel} (lf={st['lf']})")
            if st["bom"]:
                violations.append(f"BOM: {rel}")

    if args.check:
        if violations:
            print("FAIL", file=sys.stderr)
            for v in violations:
                print(f"  - {v}", file=sys.stderr)
            return 1
        print("OK")
        return 0

    version = _get_version()
    sys.stdout.write(render_markdown(rows, version))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
